name: "Presentation"

web: "[http://sharedhat.com](http://sharedhat.com)"

description: ""

authors: "[Noritaka Horio](http://sharedhat.com)"

license: "[MIT License](http://holyshared.github.com/Presentation/license.txt)"

copyright: "&copy; [Noritaka Horio](http://sharedhat.com)"

sources:
  - "Source/Presentation.js"
  - "Source/Presentation.Filter.js"

author: Noritaka Horio

category: Widgets

tags: [utils, slide]

current: 1.0

#docs: http://holyshared.github.com/Mixin/docs

demo: http://holyshared.github.com/Presentation/