name: "Presentation"

web: "[http://sharedhat.com](http://sharedhat.com)"

description: ""

authors: "[Noritaka Horio](http://sharedhat.com)"

license: "[MIT License](http://holyshared.github.com/Presentation/license.txt)"

copyright: "&copy; [Noritaka Horio](http://sharedhat.com)"

sources:
  - "Source/Core/Presentation.js"
  - "Source/Filter/Filter.js"
  - "Source/Helper/Helper.js"
  - "Source/Bootstrap/FontScaler.js"
  - "Source/Bootstrap/Filter.js"
  - "Source/Bootstrap/Helper.js"
  - "Source/Helper/Swipe.js"
  - "Source/Helper/Keyboard.js"
  - "Source/Helper/Controller.js"
  - "Source/Helper/Page.js"

author: Noritaka Horio

category: Widgets

tags: [utils, slide, presentation]

current: 1.0

#docs: http://holyshared.github.com/Mixin/docs

demo: http://holyshared.github.com/Presentation/